### ISSUE TITLE
does not work sadly

### ISSUE THREAD

**Issue by ghost** [feynlee/whisper2subtitles#1]
i am trying to transcript to a yt video but it says 
`TypeError                                 Traceback (most recent call last)

<ipython-input-13-6941cbcfa627> in <module>
      7 #@markdown Where to save the video and subtitle.
      8 save_path = 'data'  #@param {type: 'string'}
----> 9 save_path = Path(save_path)
     10 save_path.mkdir(exist_ok=True, parents=True)
     11 #@markdown What to name the saved video and subtitle.

TypeError: 'str' object is not callable
`

**Comment by feynlee** [comment]
@toprak Thanks for the feedback. It should be fixed now.

**Comment by ghost** [comment]
@feynlee its working now thank you! Can you add multiple youtube video transcribing, its really good strategy to take your lectures as output

**Comment by easyspace** [comment]
Not working again, sadly. The part where you enter the YT link and click the arrow, it spews up errors after some initialisation.
